## Contoso's Open API Yaml

info:
  contact:
    name: Contoso, Inc.
    url: https://www.contoso.org
  description: This contains the definition of a Redfish service with Contoso's OEM extensions.
  title: Redfish
  version: 'Contoso-2020.3-1.0.0'
  x-copyright: Copyright 2020 DMTF and Contoso. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright. For the full Contoso's copyright, visit https://www.contoso.org

openapi: 3.0.1

paths:
  /redfish/v1/Contoso/blah:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: http://www.contoso.org/schemas/v1/ServiceRoot.v1_9_0.yaml#/components/schemas/ServiceRoot_v1_9_0_ServiceRoot
          description: The response contains a representation of the ServiceRoot resource
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Bad/Error condition
  /redfish/v1/Contoso/blahblah:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: http://www.contoso.org/schemas/v1/ServiceRoot.v1_9_0.yaml#/components/schemas/ServiceRoot_v1_9_0_ServiceRoot
          description: The response contains a representation of the ServiceRoot resource
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Bad/Error condition


